acinclude.m4: Fix -Werror=implicit-function-declaration
```
checking snprintf format for long long int... none
configure: error: cannot determine snprintf format string for long long int

...

configure:5765: checking snprintf format for long long int
configure:5803: gcc -o conftest -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -Wall -Wshadow -Wwrite-strings -Wextra -fstack-protector -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_TIME_BITS=64 -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now conftest.c  >&5
conftest.c: In function 'does_int64_snprintf_work':
conftest.c:58:7: error: implicit declaration of function 'strcmp' [-Werror=implicit-function-declaration]
   58 |   if (strcmp(buf, "800000140000005") != 0)
      |       ^~~~~~
conftest.c:42:1: note: include '<string.h>' or provide a declaration of 'strcmp'
   41 | #include <stdio.h>
  +++ |+#include <string.h>
   42 | typedef long long int int64;
conftest.c: At top level:
conftest.c:62:1: warning: return type defaults to 'int' [-Wimplicit-int]
   62 | main() {
      | ^~~~
cc1: some warnings being treated as errors
```

Initially reported on the Debian bugtracker: https://bugs.debian.org/1065969